import { appConfig } from "../config/appConfig";
import SupabaseService from "./supabaseService";

class GeminiService {
    constructor() {
        this.apiKey = appConfig.gemini.apiKey;
        // Using gemini-2.0-flash-exp which supports multimodal generation
        this.modelName = "gemini-2.5-flash-image";
        this.apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${this.modelName}:generateContent`;
        this.supabaseService = new SupabaseService();
    }

    /**
     * Process image generation using Gemini
     */
    async generateImage({ userImageUrl, uniqueId }) {
        try {
            if (!this.apiKey) {
                throw new Error("Gemini API Key is missing");
            }

            console.log("Preparing Gemini request for model:", this.modelName);

            // Fetch images as Base64
            const userImageBase64 = await this.fetchImageAsBase64(userImageUrl);

            // Construct prompt
            const prompt = `Transform this photo into a stylized digital portrait with a painterly finish. Focus on smooth skin textures, detailed wavy hair, and soft studio lighting. Place the subject against a solid white, minimalistic background. Keep the facial features highly consistent with the original image.`;

            // Construct Request Body
            const requestBody = {
                contents: [
                    {
                        parts: [
                            { text: prompt },
                            {
                                inline_data: {
                                    mime_type: "image/jpeg",
                                    data: userImageBase64,
                                },
                            },
                        ],
                    },
                ],
                generationConfig: {
                    imageConfig: {
                        aspectRatio: "1:1"
                    }
                }
            };

            console.log("Sending request to Gemini API...");
            const response = await fetch(`${this.apiUrl}?key=${this.apiKey}`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(requestBody),
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(
                    `Gemini API Error: ${errorData.error?.message || response.statusText}`
                );
            }

            const data = await response.json();
            console.log("Received response from Gemini");

            // Parse Response
            let outputImageBase64 = null;
            let outputMimeType = "image/png";

            if (data.candidates && data.candidates.length > 0) {
                const candidate = data.candidates[0];
                if (candidate.content && candidate.content.parts) {
                    for (const part of candidate.content.parts) {
                        if (part.inlineData) {
                            outputImageBase64 = part.inlineData.data;
                            outputMimeType = part.inlineData.mimeType;
                            break;
                        }
                    }
                }
            }

            if (!outputImageBase64) {
                console.error("Gemini response:", JSON.stringify(data, null, 2));
                throw new Error("No image generated by Gemini");
            }

            // Convert Base64 to Blob
            const blob = await this.base64ToBlob(outputImageBase64, outputMimeType);

            // Upload to Supabase
            console.log("Uploading generated image to Supabase...");
            const publicUrl = await this.supabaseService.uploadImageBytes(
                blob,
                uniqueId,
                {
                    bucket: appConfig.buckets.images,
                    prefix: "output_waterpaint_",
                    extension: ".png", // forcing png extension for consistency
                }
            );

            if (!publicUrl) {
                throw new Error("Failed to upload generated image to Supabase");
            }

            // Update Database
            console.log("Updating database record...");
            await this.supabaseService.updateOutputImage(uniqueId, publicUrl);

            return publicUrl;
        } catch (error) {
            console.error("Gemini Service Error:", error);
            throw error;
        }
    }

    /**
     * Helper to fetch image from URL and convert to Base64
     */
    async fetchImageAsBase64(url) {
        try {
            const response = await fetch(url);
            if (!response.ok) throw new Error(`Failed to fetch image: ${url}`);
            const blob = await response.blob();
            return await this.blobToBase64(blob);
        } catch (error) {
            console.error("Error fetching image:", error);
            throw error;
        }
    }

    /**
     * Helper to convert Blob to Base64 string
     */
    blobToBase64(blob) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => {
                const base64String = reader.result.split(",")[1];
                resolve(base64String);
            };
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    }

    /**
     * Helper to convert Base64 string to Blob
     */
    async base64ToBlob(base64, mimeType) {
        const res = await fetch(`data:${mimeType};base64,${base64}`);
        return await res.blob();
    }
}

export default GeminiService;
